site_name: "nbcli: NetBox Command-Line Client"
site_author: Eric Geldmacher

repo_name: ericgeldmacher/nbcli
repo_url: https://github.com/ericgeldmacher/nbcli
edit_uri: ""

nav:
  - Home: index.md
  - Commands:
    - init: commands/init.md
    - search: commands/search.md
    - filter: commands/filter.md
    - create: commands/create.md
    - shell: commands/shell.md
  - Extend:
    - Views: extend/views.md
    - Command: extend/commands.md
  - Utilities: nbprint.md
  - Testing: test-env.md

theme:
  name: material
  logo: images/nbcli.svg
  favicon: images/nbcli.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - toc.integrate
  custom_dir: 'overrides/'

extra:
  version:
    provider: mike

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
