site_name: "nbcli: NetBox Command-Line Client"
site_author: Eric Geldmacher

repo_name: codeberg.org/nbcli/nbcli
repo_url: https://codeberg.org/nbcli/nbcli
edit_uri: https://codeberg.org/nbcli/nbcli/src/branch/develop/docs

nav:
  - Home: index.md
  - Get Started: quick-start.md
  - Commands:
    - init: commands/init.md
    - info: commands/info.md
    - search: commands/search.md
    - filter: commands/filter.md
    - create: commands/create.md
    - shell: commands/shell.md
  - Extend:
    - Views: extend/views.md
    - Command: extend/commands.md
  - Reference:
    - Environment Variables: reference/envars.md
    - Create Examples: reference/create-examples.md
    - nbprint(): reference/nbprint.md
  - Testing: test-env.md

theme:
  name: material
  logo: images/nbcli.svg
  favicon: images/nbcli.svg
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - toc.integrate
  custom_dir: 'overrides/'

extra:
  version:
    provider: mike

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
