steps:

  - name: lint
    image: codeberg.org/nbcli/dev-tools:latest
    pull: true
    commands:
      - flake8 . --count
    when:
      status: [ success, failure ]

  - name: format
    image: codeberg.org/nbcli/dev-tools:latest
    commands:
      - black . --check
    when:
      status: [ success, failure ]
