steps:

  - name: build
    image: codeberg.org/nbcli/dev-tools:latest
    pull: true
    commands:
      - python3 -m build
      - twine check dist/*
    when:
      event: [push]

  - name: publish
    image: codeberg.org/nbcli/dev-tools:latest
    environment:
      TWINE_USERNAME:
        from_secret: pypi_username
      TWINE_PASSWORD:
        from_secret: pypi_nbcli_token
    commands:
      - python3 -m build
      - twine check dist/*
      - twine upload dist/*
    when:
      event: tag
      ref: refs/tags/v*

when:
  branch: [ release, develop ]
  event: [ push, tag ]
